= Demonstração Blockchain
:author: Paulo Jerônimo
:toc:
:toc-title: Conteúdo
:toclevels: 4
:numbered:

:blockchain: pass:[<i>blockchain</i>]

Uma aplicação web para demonstrar conceitos de básicos e fundamentais de uma {blockchain} (ou, traduzindo ao pé da letra para o português: cadeia de blocos).

Essa demonstração pode ser visualizada em duas versões:

* Versão original (em inglês) (criada por https://github.com/anders94[Anders Brownworth]): https://www.youtube.com/watch?v=_160oMzblY8[Blockchain 101 - Demo]
* Versão brasileira (criada por https://github.com/paulojeronimo[Paulo Jerônimo] para a http://blockchain4devs.com[blockchain4devs.com]):

Através dos vídeos acima é feita uma apresentação, visual, que consideramos ser bastante elucidante para os conceitos por trás de uma {blockchain}.
É introduzido o conceito de um https://pt.wikipedia.org/wiki/Raz%C3%A3o_(contabilidade)[livro-razão] (distribuído) um aplicação web interativa.
Ela está disponível em:

http://anders.com/blockchain/

== Instalação/configuração

=== Direta, utilizando o teu próprio sistema operacional (SO)

Baixe o código:

[source,bash]
----
git clone https://github.com/anders94/blockchain-demo.git
----

Instale as dependências:

----
cd blockchain-demo
npm install
----

Execute o servidor:

----
./bin/www
----

Abra o teu browser e acesse a URL da página de demonstração: http://localhost:3000.

=== Utilizando o Docker

Baixe o código:

----
git clone https://github.com/anders94/blockchain-demo.git
----

Faça a construção do contêiner Docker:

----
cd blockchain-demo
docker-compose up -d
----

Abra o teu browser e acesse a URL da página de demonstração: http://localhost:3000.

[NOTE]
====
Se você estiver utilizando outro SO que não o Linux, macOS por exemplo, antes de executar o `docker-compose`, será necessário a instalação e a configuração do https://docs.docker.com/machine/[docker-machine].
Além disso, a URL que você acessará no browser não estará em `localhost`.
Nesse caso, siga os passos no subtópico a seguir.
Ele demonstra como utilizar o `docker-machine` para criar uma máquina virtual utilizando o https://virtualbox.org[VirtualBox].
====

==== Numa máquina virtual (criada no VirtualBox e gerenciada pelo docker-machine)

----
docker-machine create --driver virtualbox default
eval "$(docker-machine env default)"
----

Abra o teu browser e acesse a URL da página de demonstração que devera ser `http://<ip-no-docker-machine>:3000`.

[NOTE]
====
O comando `docker-machine ip` pode ser chamada para determinar o IP da máquina virtual executando o docker.
Então, no macOS, o seguinte comando pode ser utilizado para abrir a browser na URL da demonstração:

----
open http://$(docker-machine ip):3000
----
====

== Demonstração, passo a passo

=== Entendendo o que são hashes

Hashes são parte de várias informações armazenadas na {blockchain}.

Via linha de comando também é possível gerar o hash de uma string informada no quadro da aba `Hash`. Para testar isso, num macOS, execute:
----
echo -n 'Paulo Jerônimo'|shasum -a 256
----

== Envie seu obrigado

Bitcoin é aceito agradecidamente neste endereço: `1K3NvcuZzVTueHW1qhkG2Cm3viRkh2EXJp`
