[[instalacao-via-docker]]
= Utilizando o Docker

Baixe o código:

[source,bash,subs="attributes"]
----
git clone {uri-blockchain-demo-src}
----

Faça a construção do contêiner Docker:

----
cd blockchain-demo
docker-compose up -d
----

Abra o teu browser e acesse a URL da página de demonstração: http://localhost:3000.

[NOTE]
====
Se você estiver utilizando outro SO que não o Linux (um {macOS} por exemplo) antes de executar o `docker-compose`, será necessário a instalação e a configuração do {uri-docker-machine}[docker-machine].
Além disso, a URL que você acessará no browser não estará em `localhost`.
Nesse caso, siga os passos no subtópico a seguir.
Ele demonstra como utilizar o `docker-machine` para criar uma máquina virtual utilizando o {uri-virtualbox}[VirtualBox].
====

[[instalacao-via-docker-virtualbox]]
== Numa máquina virtual (criada no VirtualBox e gerenciada pelo docker-machine)

----
docker-machine create --driver virtualbox default
eval "$(docker-machine env default)"
----

Abra o teu browser e acesse a URL da página de demonstração que devera ser `http://<ip-no-docker-machine>:3000`.

[NOTE]
====
O comando `docker-machine ip` pode ser chamada para determinar o IP da máquina virtual executando o docker.
Então, no {macOS}, o seguinte comando pode ser utilizado para abrir a browser na URL da demonstração:

----
open http://$(docker-machine ip):3000
----
====
